# Generated by Django 4.2.30 on 2026-05-28 19:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address_user_avatar_user_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_professionals',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_users', to=settings.AUTH_USER_MODEL, verbose_name='Profesionales Favoritos'),
        ),
    ]
