# Generated by Django 4.2.30 on 2026-06-11 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_fcm_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
            },
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='service_radius',
            field=models.IntegerField(default=10, verbose_name='Radio de servicio (km)'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='tiktok_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='TikTok URL'),
        ),
        migrations.CreateModel(
            name='ProfessionalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/', verbose_name='Imagen de Portafolio')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='users.professionalprofile', verbose_name='Perfil Profesional')),
            ],
            options={
                'verbose_name': 'Foto de Portafolio',
                'verbose_name_plural': 'Fotos de Portafolio',
            },
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='professionals', to='users.tag', verbose_name='Etiquetas'),
        ),
    ]
