# Generated by Django 4.2.30 on 2026-06-11 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_tag_professionalprofile_facebook_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Documento')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Archivo del Documento')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible en Perfil Público')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20, verbose_name='Estado de Validación')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Motivo de Rechazo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.professionalprofile', verbose_name='Perfil Profesional')),
            ],
            options={
                'verbose_name': 'Documento Profesional',
                'verbose_name_plural': 'Documentos Profesionales',
            },
        ),
    ]
