# Generated by Django 4.2.30 on 2026-07-07 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_professionaldocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='profile_specialties', to='users.specialty', verbose_name='Especialidades'),
        ),
        migrations.AddField(
            model_name='tag',
            name='synonyms',
            field=models.TextField(blank=True, help_text='Sinónimos o palabras clave de búsqueda separadas por comas (ej: gafiter, plomeria, cañeria)', null=True, verbose_name='Sub-etiquetas ocultas'),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professionals', to='users.specialty', verbose_name='Especialidad Principal'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='specialty_icons/', verbose_name='Icono'),
        ),
    ]
