# Generated by Django 4.2.30 on 2026-07-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_subscriptionplan_professionalprofile_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='synonyms',
            field=models.TextField(blank=True, help_text='Sinónimos o palabras clave de búsqueda separadas por comas (ej: electricidad, corriente)', null=True, verbose_name='Sub-etiquetas ocultas'),
        ),
    ]
