# Generated by Django 4.2.30 on 2026-07-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#0B6E4F', help_text='Color para la etiqueta en formato hexadecimal (ej: #FF5733)', max_length=7, verbose_name='Color hexadecimal'),
        ),
    ]
