# Generated by Django 4.2.30 on 2026-07-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_tag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='color',
            field=models.CharField(default='#0B6E4F', help_text='Color para la especialidad/etiqueta en formato hexadecimal (ej: #FF5733)', max_length=7, verbose_name='Color hexadecimal'),
        ),
    ]
