# Generated by Django 4.2.30 on 2026-07-17 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_tag_specialty_alter_tag_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('color', models.CharField(default='#0B6E4F', help_text='Color para la sub-etiqueta en formato hexadecimal (ej: #FF5733)', max_length=7, verbose_name='Color hexadecimal')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtags', to='users.tag', verbose_name='Etiqueta Principal (Subclase)')),
            ],
            options={
                'verbose_name': 'Especialización (Sub-etiqueta)',
                'verbose_name_plural': 'Especializaciones (Sub-etiquetas)',
                'unique_together': {('tag', 'name')},
            },
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='subtags',
            field=models.ManyToManyField(blank=True, related_name='professionals', to='users.subtag', verbose_name='Especializaciones'),
        ),
    ]
