# Generated by Django 4.2.30 on 2026-07-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_subtag_professionalprofile_subtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_emergency',
            field=models.BooleanField(default=False, verbose_name='Modo Urgencia'),
        ),
    ]
