# Generated by Django 4.2.30 on 2026-07-17 21:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_is_emergency'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('otp_code', models.CharField(max_length=6, verbose_name='Código OTP')),
                ('reset_token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Token de cambio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Fecha de expiración')),
                ('used', models.BooleanField(default=False, verbose_name='Usado')),
                ('verified', models.BooleanField(default=False, verbose_name='Verificado')),
            ],
            options={
                'verbose_name': 'OTP de recuperación de contraseña',
                'verbose_name_plural': 'OTPs de recuperación de contraseña',
            },
        ),
    ]
