# Generated by Django 4.2.30 on 2026-07-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_userdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_specialties_per_tradesman', models.PositiveIntegerField(default=6, help_text='Número máximo de especialidades/subtags que puede seleccionar un maestro', verbose_name='Máximo de especialidades por maestro')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
            },
        ),
    ]
