# Generated by Django on 2026-07-27

from django.db import migrations, models

def seed_subscription_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model('users', 'SubscriptionPlan')

    # Plan Básico
    basico, _ = SubscriptionPlan.objects.get_or_create(
        name="Básico",
        defaults={"description": "Plan básico gratuito"}
    )
    basico.price = 0.00
    basico.duration_days = 30
    basico.monthly_requests = 4
    basico.urgent_requests = 1
    basico.service_categories = 2
    basico.search_position = "Estándar"
    basico.featured_badge = "—"
    basico.rrss_campaigns = "—"
    basico.radio_broadcast = "—"
    basico.profile_statistics = "Básicas"
    basico.support_level = "Estándar"
    basico.save()

    # Also update any existing 'Plan Base' if created earlier
    SubscriptionPlan.objects.filter(name="Plan Base").update(
        name="Básico",
        monthly_requests=4,
        urgent_requests=1,
        service_categories=2,
        search_position="Estándar",
        featured_badge="—",
        rrss_campaigns="—",
        radio_broadcast="—",
        profile_statistics="Básicas",
        support_level="Estándar"
    )

    # Plan Profesional
    profesional, _ = SubscriptionPlan.objects.get_or_create(
        name="Profesional",
        defaults={"description": "Plan recomendado para profesionales activos"}
    )
    profesional.price = 9990.00
    profesional.duration_days = 30
    profesional.monthly_requests = 25
    profesional.urgent_requests = 8
    profesional.service_categories = 6
    profesional.search_position = "Preferente"
    profesional.featured_badge = "Destacada"
    profesional.rrss_campaigns = "Ocasional"
    profesional.radio_broadcast = "—"
    profesional.profile_statistics = "Intermedias"
    profesional.support_level = "Prioritario"
    profesional.save()

    # Plan Premium
    premium, _ = SubscriptionPlan.objects.get_or_create(
        name="Premium",
        defaults={"description": "Plan completo con máxima visibilidad y beneficios ilimitados"}
    )
    premium.price = 19990.00
    premium.duration_days = 30
    premium.monthly_requests = None
    premium.urgent_requests = None
    premium.service_categories = None
    premium.search_position = "Prioridad máxima"
    premium.featured_badge = "Premium"
    premium.rrss_campaigns = "Prioritaria"
    premium.radio_broadcast = "Elegible"
    premium.profile_statistics = "Completas"
    premium.support_level = "Preferente"
    premium.save()

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_user_client_session_key_user_tradesman_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='featured_badge',
            field=models.CharField(blank=True, default='—', max_length=100, null=True, verbose_name='Insignia destacada'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='monthly_requests',
            field=models.IntegerField(blank=True, help_text='Nulo/vacío para ilimitadas', null=True, verbose_name='Solicitudes mensuales'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='profile_statistics',
            field=models.CharField(default='Básicas', max_length=100, verbose_name='Estadísticas del perfil'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='radio_broadcast',
            field=models.CharField(blank=True, default='—', max_length=100, null=True, verbose_name='Difusión radial'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='rrss_campaigns',
            field=models.CharField(blank=True, default='—', max_length=100, null=True, verbose_name='Aparición en campañas RRSS'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='search_position',
            field=models.CharField(default='Estándar', max_length=100, verbose_name='Posición en búsquedas'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='service_categories',
            field=models.IntegerField(blank=True, help_text='Nulo/vacío para ilimitadas', null=True, verbose_name='Categorías de servicio'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='support_level',
            field=models.CharField(default='Estándar', max_length=100, verbose_name='Soporte'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='urgent_requests',
            field=models.IntegerField(blank=True, help_text='Nulo/vacío para ilimitadas', null=True, verbose_name='Solicitudes urgentes'),
        ),
        migrations.RunPython(seed_subscription_plans, reverse_code=reverse_func),
    ]
