# Generated by Django 4.2.30 on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_subscriptionplan_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='tag_icons/', verbose_name='Icono'),
        ),
    ]
