# Generated by Django 4.2.30 on 2026-08-05 23:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_tag_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='plan_start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de inicio del plan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_completed_jobs',
            field=models.IntegerField(blank=True, help_text='Nulo para ilimitados. Usado principalmente para planes iniciales.', null=True, verbose_name='Límite de trabajos terminados'),
        ),
    ]
