# Generated by Django 4.2.30 on 2026-08-05 23:54

from django.db import migrations

def create_initial_plan(apps, schema_editor):
    SubscriptionPlan = apps.get_model('users', 'SubscriptionPlan')
    SubscriptionPlan.objects.get_or_create(
        name='Plan Inicial',
        defaults={
            'description': 'Suscripción de prueba inicial',
            'price': 0.00,
            'duration_days': 30,
            'max_completed_jobs': 3,
            'service_categories': None,
        }
    )

def reverse_initial_plan(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_professionalprofile_plan_start_date_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_plan, reverse_initial_plan),
    ]
