# Generated by Django 4.2.30 on 2026-08-07 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_create_initial_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['display_order', 'id'], 'verbose_name': 'Plan de Suscripción', 'verbose_name_plural': 'Planes de Suscripción'},
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Menor número aparece primero (1, 2, 3...).', verbose_name='Orden de visualización'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_coming_soon',
            field=models.BooleanField(default=False, help_text='Si está activado, el plan se muestra pero no puede ser seleccionado.', verbose_name='Próximamente'),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='plan_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de inicio del plan'),
        ),
    ]
