# Generated by Django 4.2.30 on 2026-08-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_migrate_legacy_specialties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='client_session_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Clave de Sesión Cliente Activa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Disponible para trabajos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tradesman_session_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Clave de Sesión Maestro Activa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CUSTOMER', 'Cliente'), ('PROFESSIONAL', 'Profesional'), ('ADMIN', 'Administrador')], db_index=True, default='CUSTOMER', max_length=20, verbose_name='Tipo de Usuario'),
        ),
    ]
