# Generated by Django 4.2.30 on 2026-08-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_user_client_session_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_type', models.CharField(choices=[('CLIENT', 'Cliente'), ('TRADESMAN', 'Especialista / Maestro')], max_length=20, unique=True, verbose_name='Aplicación')),
                ('min_version', models.CharField(default='1.0.0', help_text='Versiones inferiores a esta serán bloqueadas en el inicio de la app.', max_length=20, verbose_name='Versión Mínima Obligatoria')),
                ('latest_version', models.CharField(default='1.0.0', help_text='Versión recomendada en las tiendas.', max_length=20, verbose_name='Última Versión Disponible')),
                ('store_url_android', models.URLField(blank=True, null=True, verbose_name='URL Play Store (Android)')),
                ('store_url_ios', models.URLField(blank=True, null=True, verbose_name='URL App Store (iOS)')),
                ('title', models.CharField(default='Actualización Requerida', max_length=100, verbose_name='Título del Diálogo')),
                ('message', models.TextField(default='Para continuar usando Clanship de manera segura, por favor actualiza la aplicación a la última versión disponible.', verbose_name='Mensaje de Bloqueo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Control de Versión Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Versión de App',
                'verbose_name_plural': 'Configuración de Versiones de Apps',
            },
        ),
    ]
