# Generated by Django 4.2.30 on 2026-08-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_appversionconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Motivo por el cual se rechazó o se observaron los documentos/perfil.', null=True, verbose_name='Motivo de Rechazo'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de Revisión'), ('APPROVED', 'Aprobado / Habilitado'), ('REJECTED', 'Rechazado / Observado')], default='PENDING', max_length=20, verbose_name='Estado de Verificación'),
        ),
    ]
