# Generated by Django 4.2 on 2026-08-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_professionalprofile_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalprofile',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Verificado'),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de Revisión'), ('APPROVED', 'Aprobado / Habilitado'), ('REJECTED', 'Rechazado / Observado')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado de Verificación'),
        ),
    ]
