# Generated by Django 4.2 on 2026-08-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_professionalprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='subscriptions_enabled_ios',
            field=models.BooleanField(
                default=False,
                help_text='Controla si en iOS se muestran compras/suscripciones de planes o vista informativa (Mantener en False para revisión de Apple)',
                verbose_name='Habilitar suscripciones en iOS',
            ),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='subscriptions_enabled_android',
            field=models.BooleanField(
                default=True,
                help_text='Controla si en Android se muestran los planes de suscripción',
                verbose_name='Habilitar suscripciones en Android',
            ),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='subscription_ios_link',
            field=models.URLField(
                default='https://clanship.cl',
                help_text='URL donde el usuario en iOS puede revisar información de planes',
                verbose_name='Link para información de planes en iOS',
            ),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='subscription_ios_message',
            field=models.TextField(
                default='Para una mejor experiencia y conocer cómo mejorar tu plan, revisa en el siguiente link:',
                help_text='Texto informativo que se mostrará en la pantalla de planes en iOS',
                verbose_name='Mensaje para iOS',
            ),
        ),
    ]
