# Generated by Django 4.2.30 on 2026-09-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_normalize_user_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Fiestas Patrias 2026', max_length=100, verbose_name='Nombre de la campaña')),
                ('season_type', models.CharField(choices=[('FIESTAS_PATRIAS', 'Fiestas Patrias (18 de Septiembre)'), ('HALLOWEEN', 'Halloween'), ('NAVIDAD', 'Navidad y Fin de Año'), ('VERANO', 'Verano'), ('CYBER', 'CyberDays / Descuentos'), ('CUSTOM', 'Personalizada')], default='CUSTOM', max_length=30, verbose_name='Festividad / Tipo')),
                ('app_type', models.CharField(choices=[('ALL', 'Todas las aplicaciones'), ('CLIENT', 'Cliente'), ('TRADESMAN', 'Especialista / Maestro')], default='CLIENT', max_length=20, verbose_name='Aplicación de destino')),
                ('is_active', models.BooleanField(default=True, help_text='Interruptor maestro (Kill switch) para encender o apagar de inmediato.', verbose_name='¿Activa?')),
                ('start_date', models.DateTimeField(verbose_name='Fecha y hora de inicio')),
                ('end_date', models.DateTimeField(verbose_name='Fecha y hora de término')),
                ('priority', models.PositiveIntegerField(default=1, help_text='Mayor valor tiene precedencia si dos campañas se solapan en fechas.', verbose_name='Prioridad')),
                ('primary_color', models.CharField(blank=True, help_text='Hexadecimal ej: #0B6E4F', max_length=9, null=True, verbose_name='Color primario')),
                ('secondary_color', models.CharField(blank=True, help_text='Hexadecimal ej: #0D2B45', max_length=9, null=True, verbose_name='Color secundario')),
                ('accent_color', models.CharField(blank=True, help_text='Hexadecimal ej: #D52B1E o #FF7518', max_length=9, null=True, verbose_name='Color de acento')),
                ('header_gradient_start', models.CharField(blank=True, help_text='Hexadecimal ej: #0D2B45', max_length=9, null=True, verbose_name='Inicio gradiente cabecera')),
                ('header_gradient_end', models.CharField(blank=True, help_text='Hexadecimal ej: #163E63', max_length=9, null=True, verbose_name='Fin gradiente cabecera')),
                ('logo_badge_icon', models.FileField(blank=True, help_text='PNG transparente o SVG (chupalla, gorro navideño, calabaza)', null=True, upload_to='seasonal/badges/', verbose_name='Insignia para logo/avatar')),
                ('banner_image', models.ImageField(blank=True, help_text='Imagen opcional para el banner principal', null=True, upload_to='seasonal/banners/', verbose_name='Imagen de banner de fondo')),
                ('particle_effect', models.CharField(choices=[('NONE', 'Ninguno'), ('CONFETTI', 'Confeti / Challa (Fiestas Patrias / Año Nuevo)'), ('SNOW', 'Nieve (Navidad)'), ('STARS', 'Estrellas / Destellos')], default='NONE', max_length=20, verbose_name='Efecto de partículas')),
                ('greeting_prefix', models.CharField(blank=True, help_text="Ej: '¡Tikitikiti!', '¡Feliz Navidad!', '¡Feliz 18!'", max_length=60, null=True, verbose_name='Prefijo de saludo')),
                ('promo_banner_title', models.CharField(blank=True, help_text='Ej: ¡Celebra el 18 sin preocupaciones!', max_length=120, null=True, verbose_name='Título del banner')),
                ('promo_banner_subtitle', models.CharField(blank=True, help_text='Ej: Parrilleros, gasfitería y electricidad para tu fonda o casa.', max_length=220, null=True, verbose_name='Subtítulo del banner')),
                ('promo_banner_cta_text', models.CharField(blank=True, help_text='Ej: Pedir Especialista', max_length=50, null=True, verbose_name='Texto botón acción (CTA)')),
                ('promo_banner_action_type', models.CharField(choices=[('REQUEST_JOB', 'Abrir creación de solicitud'), ('SEARCH_TAG', 'Filtrar por etiqueta / especialidad'), ('DEEP_LINK', 'Abrir enlace externo / WebView')], default='REQUEST_JOB', max_length=20, verbose_name='Tipo de acción')),
                ('promo_banner_action_value', models.CharField(blank=True, help_text='Nombre de especialidad a buscar o URL externa', max_length=200, null=True, verbose_name='Valor de acción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured_tags', models.ManyToManyField(blank=True, related_name='seasonal_campaigns', to='users.tag', verbose_name='Etiquetas destacadas')),
            ],
            options={
                'verbose_name': 'Campaña de Temporada / Festividad',
                'verbose_name_plural': 'Campañas de Temporada / Festividades',
                'ordering': ['-priority', '-start_date'],
            },
        ),
    ]
