# Generated by Django 4.2.30 on 2026-09-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_seasonalcampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonalcampaign',
            name='nav_center_color',
            field=models.CharField(blank=True, help_text='Hexadecimal ej: #D52B1E. Si está vacío, usa el color primario.', max_length=9, null=True, verbose_name='Color botón central del menú'),
        ),
        migrations.AddField(
            model_name='seasonalcampaign',
            name='nav_center_icon',
            field=models.FileField(blank=True, help_text='PNG transparente para reemplazar el icono de explorar/mapa en el menú inferior', null=True, upload_to='seasonal/nav_icons/', verbose_name='Icono central de navegación (PNG)'),
        ),
        migrations.AddField(
            model_name='seasonalcampaign',
            name='search_bar_border_color',
            field=models.CharField(blank=True, help_text='Hexadecimal ej: #D52B1E. Si está vacío, usa el color de acento.', max_length=9, null=True, verbose_name='Color borde buscador Home'),
        ),
    ]
