# Generated by Django 4.2.30 on 2026-09-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_seasonalcampaign_nav_center_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonalcampaign',
            name='custom_garland_image',
            field=models.FileField(blank=True, help_text='Opcional: PNG transparente que reemplaza la guirnalda automática.', null=True, upload_to='seasonal/garlands/', verbose_name='Imagen de guirnalda personalizada (PNG)'),
        ),
        migrations.AddField(
            model_name='seasonalcampaign',
            name='show_top_garland',
            field=models.BooleanField(default=False, help_text='Activa una fila decorativa superior: Banderas chilenas (Fiestas Patrias), Murciélagos (Halloween) o Guirnaldas (Navidad).', verbose_name='¿Mostrar guirnalda superior?'),
        ),
    ]
