# Generated by Django 4.2.30 on 2026-09-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_seasonalcampaign_custom_garland_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonalcampaign',
            name='garland_position',
            field=models.CharField(choices=[('BOTH', 'En ambos (Barra superior y Card principal)'), ('TOP', 'Solo arriba (Barra superior / Nombre)'), ('BOTTOM', 'Solo abajo (Card principal / Banner)')], default='BOTH', help_text='Controla si las guirnaldas aparecen arriba (en la barra superior), abajo (en el card principal), o en ambos lugares.', max_length=20, verbose_name='Ubicación de guirnaldas'),
        ),
        migrations.AlterField(
            model_name='seasonalcampaign',
            name='show_top_garland',
            field=models.BooleanField(default=False, help_text='Activa la fila decorativa de guirnaldas (Banderas chilenas, Murciélagos o Guirnalda de pino).', verbose_name='¿Mostrar guirnaldas / banderines?'),
        ),
    ]
