# Generated by Django 4.2.30 on 2026-09-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_seasonalcampaign_garland_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonalcampaign',
            name='stat_cards_bg_color',
            field=models.CharField(blank=True, help_text='Hexadecimal ej: #F1F5F9 o #0D2B45 para las 4 tarjetas de solicitudes en la app de maestro.', max_length=9, null=True, verbose_name='Color fondo cuadros de solicitudes'),
        ),
        migrations.AddField(
            model_name='seasonalcampaign',
            name='stat_cards_bg_image',
            field=models.ImageField(blank=True, help_text='Imagen opcional (textura, patrón o festividad) para el fondo de las 4 tarjetas de solicitudes en la app de maestro.', null=True, upload_to='seasonal/stat_cards/', verbose_name='Imagen de fondo cuadros de solicitudes'),
        ),
    ]
