# Generated by Django 4.2.30 on 2026-09-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_seasonalcampaign_stat_cards_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonalcampaign',
            name='stat_card_active_bg_color',
            field=models.CharField(blank=True, help_text='Hexadecimal ej: #F1F5F9 o #0D2B45.', max_length=9, null=True, verbose_name='Color fondo: Solicitudes de Trabajo (Activas)'),
        ),
        migrations.AddField(
            model_name='seasonalcampaign',
            name='stat_card_active_bg_image',
            field=models.ImageField(blank=True, help_text='Imagen específica para la tarjeta de Solicitudes de Trabajo.', null=True, upload_to='seasonal/stat_cards/', verbose_name='Imagen fondo: Solicitudes de Trabajo (Activas)'),
        ),
        migrations.AddField(
            model_name='seasonalcampaign',
            name='stat_card_completed_bg_color',
            field=models.CharField(blank=True, help_text='Hexadecimal ej: #ECFDF5 (verde menta suave).', max_length=9, null=True, verbose_name='Color fondo: Solicitudes Completadas'),
        ),
        migrations.AddField(
            model_name='seasonalcampaign',
            name='stat_card_completed_bg_image',
            field=models.ImageField(blank=True, help_text='Imagen específica para la tarjeta de Solicitudes Completadas.', null=True, upload_to='seasonal/stat_cards/', verbose_name='Imagen fondo: Solicitudes Completadas'),
        ),
        migrations.AddField(
            model_name='seasonalcampaign',
            name='stat_card_rejected_bg_color',
            field=models.CharField(blank=True, help_text='Hexadecimal ej: #FEF2F2 (rojo suave).', max_length=9, null=True, verbose_name='Color fondo: Solicitudes Rechazadas'),
        ),
        migrations.AddField(
            model_name='seasonalcampaign',
            name='stat_card_rejected_bg_image',
            field=models.ImageField(blank=True, help_text='Imagen específica para la tarjeta de Solicitudes Rechazadas.', null=True, upload_to='seasonal/stat_cards/', verbose_name='Imagen fondo: Solicitudes Rechazadas'),
        ),
        migrations.AddField(
            model_name='seasonalcampaign',
            name='stat_card_scheduled_bg_color',
            field=models.CharField(blank=True, help_text='Hexadecimal ej: #FFFBEB (ámbar suave).', max_length=9, null=True, verbose_name='Color fondo: Solicitudes Programadas'),
        ),
        migrations.AddField(
            model_name='seasonalcampaign',
            name='stat_card_scheduled_bg_image',
            field=models.ImageField(blank=True, help_text='Imagen específica para la tarjeta de Solicitudes Programadas.', null=True, upload_to='seasonal/stat_cards/', verbose_name='Imagen fondo: Solicitudes Programadas'),
        ),
        migrations.AlterField(
            model_name='seasonalcampaign',
            name='stat_cards_bg_color',
            field=models.CharField(blank=True, help_text='Hexadecimal ej: #F1F5F9. Aplica a todas las tarjetas de solicitudes que no tengan un color específico.', max_length=9, null=True, verbose_name='Color fondo cuadros (General / Fallback)'),
        ),
        migrations.AlterField(
            model_name='seasonalcampaign',
            name='stat_cards_bg_image',
            field=models.ImageField(blank=True, help_text='Imagen para las tarjetas que no tengan una imagen específica.', null=True, upload_to='seasonal/stat_cards/', verbose_name='Imagen de fondo cuadros (General / Fallback)'),
        ),
    ]
