# Generated by Django 4.2.30 on 2026-09-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_seasonalcampaign_stat_card_active_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonalcampaign',
            name='stat_card_active_icon_color',
            field=models.CharField(blank=True, help_text='Hexadecimal ej: #2E3135.', max_length=9, null=True, verbose_name='Color icono: Solicitudes de Trabajo'),
        ),
        migrations.AddField(
            model_name='seasonalcampaign',
            name='stat_card_active_number_color',
            field=models.CharField(blank=True, help_text='Hexadecimal ej: #2E3135 o #0D2B45.', max_length=9, null=True, verbose_name='Color número: Solicitudes de Trabajo'),
        ),
        migrations.AddField(
            model_name='seasonalcampaign',
            name='stat_card_active_text_color',
            field=models.CharField(blank=True, help_text='Hexadecimal ej: #2E3135.', max_length=9, null=True, verbose_name='Color texto: Solicitudes de Trabajo'),
        ),
        migrations.AddField(
            model_name='seasonalcampaign',
            name='stat_card_completed_icon_color',
            field=models.CharField(blank=True, help_text='Hexadecimal ej: #0B6E4F.', max_length=9, null=True, verbose_name='Color icono: Solicitudes Completadas'),
        ),
        migrations.AddField(
            model_name='seasonalcampaign',
            name='stat_card_completed_number_color',
            field=models.CharField(blank=True, help_text='Hexadecimal ej: #0B6E4F.', max_length=9, null=True, verbose_name='Color número: Solicitudes Completadas'),
        ),
        migrations.AddField(
            model_name='seasonalcampaign',
            name='stat_card_completed_text_color',
            field=models.CharField(blank=True, help_text='Hexadecimal ej: #2E3135.', max_length=9, null=True, verbose_name='Color texto: Solicitudes Completadas'),
        ),
        migrations.AddField(
            model_name='seasonalcampaign',
            name='stat_card_rejected_icon_color',
            field=models.CharField(blank=True, help_text='Hexadecimal ej: #EA4335.', max_length=9, null=True, verbose_name='Color icono: Solicitudes Rechazadas'),
        ),
        migrations.AddField(
            model_name='seasonalcampaign',
            name='stat_card_rejected_number_color',
            field=models.CharField(blank=True, help_text='Hexadecimal ej: #EA4335.', max_length=9, null=True, verbose_name='Color número: Solicitudes Rechazadas'),
        ),
        migrations.AddField(
            model_name='seasonalcampaign',
            name='stat_card_rejected_text_color',
            field=models.CharField(blank=True, help_text='Hexadecimal ej: #2E3135.', max_length=9, null=True, verbose_name='Color texto: Solicitudes Rechazadas'),
        ),
        migrations.AddField(
            model_name='seasonalcampaign',
            name='stat_card_scheduled_icon_color',
            field=models.CharField(blank=True, help_text='Hexadecimal ej: #F28C28.', max_length=9, null=True, verbose_name='Color icono: Solicitudes Programadas'),
        ),
        migrations.AddField(
            model_name='seasonalcampaign',
            name='stat_card_scheduled_number_color',
            field=models.CharField(blank=True, help_text='Hexadecimal ej: #F28C28.', max_length=9, null=True, verbose_name='Color número: Solicitudes Programadas'),
        ),
        migrations.AddField(
            model_name='seasonalcampaign',
            name='stat_card_scheduled_text_color',
            field=models.CharField(blank=True, help_text='Hexadecimal ej: #2E3135.', max_length=9, null=True, verbose_name='Color texto: Solicitudes Programadas'),
        ),
        migrations.AddField(
            model_name='seasonalcampaign',
            name='stat_cards_icon_color',
            field=models.CharField(blank=True, help_text='Hexadecimal ej: #0B6E4F para el icono y halo de las tarjetas.', max_length=9, null=True, verbose_name='Color iconos tarjetas (General / Fallback)'),
        ),
        migrations.AddField(
            model_name='seasonalcampaign',
            name='stat_cards_number_color',
            field=models.CharField(blank=True, help_text='Hexadecimal ej: #0B6E4F para el número grande de las tarjetas.', max_length=9, null=True, verbose_name='Color números tarjetas (General / Fallback)'),
        ),
        migrations.AddField(
            model_name='seasonalcampaign',
            name='stat_cards_text_color',
            field=models.CharField(blank=True, help_text='Hexadecimal ej: #2E3135 para la etiqueta de las tarjetas.', max_length=9, null=True, verbose_name='Color textos tarjetas (General / Fallback)'),
        ),
    ]
