# Generated by Django 4.2.30 on 2026-09-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_seasonalcampaign_stat_card_active_icon_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonalcampaign',
            name='stat_card_active_image_opacity',
            field=models.PositiveSmallIntegerField(blank=True, help_text='0 a 100% de visibilidad.', null=True, verbose_name='Opacidad imagen: Solicitudes de Trabajo (%)'),
        ),
        migrations.AddField(
            model_name='seasonalcampaign',
            name='stat_card_completed_image_opacity',
            field=models.PositiveSmallIntegerField(blank=True, help_text='0 a 100% de visibilidad.', null=True, verbose_name='Opacidad imagen: Solicitudes Completadas (%)'),
        ),
        migrations.AddField(
            model_name='seasonalcampaign',
            name='stat_card_rejected_image_opacity',
            field=models.PositiveSmallIntegerField(blank=True, help_text='0 a 100% de visibilidad.', null=True, verbose_name='Opacidad imagen: Solicitudes Rechazadas (%)'),
        ),
        migrations.AddField(
            model_name='seasonalcampaign',
            name='stat_card_scheduled_image_opacity',
            field=models.PositiveSmallIntegerField(blank=True, help_text='0 a 100% de visibilidad.', null=True, verbose_name='Opacidad imagen: Solicitudes Programadas (%)'),
        ),
        migrations.AddField(
            model_name='seasonalcampaign',
            name='stat_cards_image_opacity',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Porcentaje de 0 a 100% (ej: 25 para marca de agua sutil, 75 para imagen visible, 100 para foto completa sin filtro). Aplica a las que no definan un porcentaje propio.', null=True, verbose_name='Opacidad imagen tarjetas - General (%)'),
        ),
    ]
