# Generated by Django 4.2.30 on 2026-09-10 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def populate_referral_codes(apps, schema_editor):
    import secrets
    ProfessionalProfile = apps.get_model('users', 'ProfessionalProfile')
    SubscriptionPlan = apps.get_model('users', 'SubscriptionPlan')
    SystemSetting = apps.get_model('users', 'SystemSetting')

    chars = "23456789ABCDEFGHJKLMNPQRSTUVWXYZ"
    existing_codes = set(ProfessionalProfile.objects.exclude(referral_code__isnull=True).values_list('referral_code', flat=True))

    for profile in ProfessionalProfile.objects.filter(referral_code__isnull=True):
        while True:
            code = f"CLAN-{''.join(secrets.choice(chars) for _ in range(5))}"
            if code not in existing_codes:
                existing_codes.add(code)
                profile.referral_code = code
                profile.save(update_fields=['referral_code'])
                break

    setting = SystemSetting.objects.first()
    if setting and not setting.referral_reward_plan_id:
        reward_plan = SubscriptionPlan.objects.filter(name__icontains="Profesional").first() or SubscriptionPlan.objects.filter(price__gt=0).first()
        if reward_plan:
            setting.referral_reward_plan = reward_plan
            setting.save(update_fields=['referral_reward_plan'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_seasonalcampaign_stat_card_active_image_opacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='plan_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de expiración del plan / beneficio'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, help_text='Código único para compartir y ganar beneficios por asociados referidos', max_length=20, null=True, unique=True, verbose_name='Código de Asociado'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='referral_eligible_user_type',
            field=models.CharField(choices=[('ALL', 'Todos (Clientes y Maestros)'), ('CUSTOMER_ONLY', 'Solo Clientes'), ('PROFESSIONAL_ONLY', 'Solo Maestros')], default='ALL', help_text='Define si suman a la meta registros de clientes, de maestros o ambos', max_length=20, verbose_name='Tipos de usuarios que suman a la meta'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='referral_program_active',
            field=models.BooleanField(default=True, help_text='Activa o desactiva el sistema de códigos de asociado', verbose_name='Programa de asociados activo'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='referral_reward_days',
            field=models.PositiveIntegerField(default=30, help_text='Días de duración que se otorgarán del plan asociado', verbose_name='Duración del beneficio (X días)'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='referral_reward_plan',
            field=models.ForeignKey(blank=True, help_text='Plan que ganará el maestro al alcanzar la meta de inscritos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_reward_settings', to='users.subscriptionplan', verbose_name='Plan otorgado por meta'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='referral_target_count',
            field=models.PositiveIntegerField(default=5, help_text='Cantidad de usuarios que deben registrarse con el código para otorgar el beneficio al maestro', verbose_name='Meta de inscritos (N personas)'),
        ),
        migrations.CreateModel(
            name='ReferralRewardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_granted', models.PositiveIntegerField(verbose_name='Días otorgados')),
                ('referrals_count_at_time', models.PositiveIntegerField(verbose_name='Inscritos acumulados a la fecha')),
                ('new_plan_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Nueva fecha de vencimiento')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de otorgamiento')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.subscriptionplan', verbose_name='Plan otorgado')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_rewards', to=settings.AUTH_USER_MODEL, verbose_name='Maestro beneficiado')),
            ],
            options={
                'verbose_name': 'Historial de Beneficio por Asociados',
                'verbose_name_plural': 'Historial de Beneficios por Asociados',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.CreateModel(
            name='AssociateReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code_used', models.CharField(max_length=50, verbose_name='Código de asociado utilizado')),
                ('reward_granted', models.BooleanField(default=False, help_text='Indica si este registro ya fue contabilizado en una meta N cumplida', verbose_name='¿Premio ya otorgado?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inscripción')),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by_relation', to=settings.AUTH_USER_MODEL, verbose_name='Usuario inscrito con el código')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL, verbose_name='Maestro que refirió')),
            ],
            options={
                'verbose_name': 'Asociado Referido',
                'verbose_name_plural': 'Asociados Referidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(populate_referral_codes, migrations.RunPython.noop),
    ]

