# Generated by Django 4.2.30 on 2026-09-10 15:52

from django.db import migrations, models


def seed_initial_content(apps, schema_editor):
    ReferralProgramContent = apps.get_model('users', 'ReferralProgramContent')
    
    # Spanish (es)
    ReferralProgramContent.objects.update_or_create(
        language='es',
        defaults={
            'is_active': True,
            'hero_title': "¡Invita y gana beneficios!",
            'hero_description': "Comparte tu código con clientes o conocidos. Cada vez que {target} personas se inscriban con tu código, ganarás {days} días de {plan} gratis.",
            'share_message': "¡Hola! Te invito a unirte a Clanship. Regístrate usando mi código de asociado {code} para contactarme y encontrar los mejores especialistas: https://clanship.cl",
            'how_it_works_title': "¿Cómo funciona?",
            'step_1': "Comparte tu código con clientes o colegas.",
            'step_2': "Al registrarse en Clanship, ingresan tu código.",
            'step_3': "Al completar {target} asociados, ganas automáticamente {days} días de {plan}.",
            'banner_title': "Mi Código de Asociado",
            'banner_subtitle': "Invita {target} asociados y gana un plan gratis",
            'my_plan_invite_text': "Invita {target} asociados y gana {days} días gratis de {plan}.",
            'active_benefit_text': "Beneficio de plan activo hasta el {date}",
            'notification_new_referral': "¡{name} se inscribió con tu código de asociado! Llevas {pending} de {target} para tu beneficio.",
            'notification_reward_earned': "¡Felicidades! Completaste tu meta de {target} asociados. Ganaste {days} días de {plan} gratis.",
            'registration_code_label': "Código de asociado o invitación (Opcional)",
            'registration_code_hint': "Ej: CLAN-ABC12",
        }
    )

    # English (en)
    ReferralProgramContent.objects.update_or_create(
        language='en',
        defaults={
            'is_active': True,
            'hero_title': "Invite & earn benefits!",
            'hero_description': "Share your code with customers or contacts. Every time {target} people register with your code, you will earn {days} days of {plan} for free.",
            'share_message': "Hello! I invite you to join Clanship. Sign up using my associate code {code} to connect with me and find top home specialists: https://clanship.cl",
            'how_it_works_title': "How does it work?",
            'step_1': "Share your code with customers or colleagues.",
            'step_2': "When registering on Clanship, they enter your code.",
            'step_3': "When completing {target} associates, you automatically earn {days} days of {plan}.",
            'banner_title': "My Associate Code",
            'banner_subtitle': "Invite {target} associates and earn a free plan",
            'my_plan_invite_text': "Invite {target} associates and earn {days} days of {plan} for free.",
            'active_benefit_text': "Active plan benefit until {date}",
            'notification_new_referral': "{name} registered with your associate code! You have {pending} of {target} towards your next reward.",
            'notification_reward_earned': "Congratulations! You completed your goal of {target} associates. You earned {days} days of {plan} for free.",
            'registration_code_label': "Associate or referral code (Optional)",
            'registration_code_hint': "E.g. CLAN-ABC12",
        }
    )

    # French (fr)
    ReferralProgramContent.objects.update_or_create(
        language='fr',
        defaults={
            'is_active': True,
            'hero_title': "Invitez et gagnez des avantages !",
            'hero_description': "Partagez votre code avec des clients ou des proches. Chaque fois que {target} personnes s'inscrivent avec votre code, vous gagnerez {days} jours de {plan} gratuitement.",
            'share_message': "Bonjour ! Je vous invite à rejoindre Clanship. Inscrivez-vous avec mon code d'associé {code} pour me contacter et trouver les meilleurs spécialistes : https://clanship.cl",
            'how_it_works_title': "Comment ça marche ?",
            'step_1': "Partagez votre code avec vos clients ou collègues.",
            'step_2': "Lors de leur inscription sur Clanship, ils saisissent votre code.",
            'step_3': "Après {target} associés inscrits, vous gagnez automatiquement {days} jours de {plan}.",
            'banner_title': "Mon Code d'Associé",
            'banner_subtitle': "Invitez {target} associés et gagnez un plan gratuit",
            'my_plan_invite_text': "Invitez {target} associés et gagnez {days} jours gratuits de {plan}.",
            'active_benefit_text': "Avantage de plan actif jusqu'au {date}",
            'notification_new_referral': "{name} s'est inscrit avec votre code d'associé ! Vous avez {pending} sur {target} pour votre prochain avantage.",
            'notification_reward_earned': "Félicitations ! Vous avez atteint votre objectif de {target} associés. Vous avez gagné {days} jours de {plan} gratuits.",
            'registration_code_label': "Code d'associé ou d'invitation (Facultatif)",
            'registration_code_hint': "Ex : CLAN-ABC12",
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_professionalprofile_plan_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralProgramContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English'), ('fr', 'Français')], default='es', help_text='Código de idioma (es, en, fr)', max_length=10, unique=True, verbose_name='Idioma')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si esta versión de textos está disponible', verbose_name='Activo')),
                ('hero_title', models.CharField(default='¡Invita y gana beneficios!', help_text='Título en la cabecera de la pantalla de asociados', max_length=200, verbose_name='Título principal')),
                ('hero_description', models.TextField(default='Comparte tu código con clientes o conocidos. Cada vez que {target} personas se inscriban con tu código, ganarás {days} días de {plan} gratis.', help_text='Variables disponibles: {target} (meta), {days} (días), {plan} (nombre del plan)', verbose_name='Descripción del beneficio')),
                ('share_message', models.TextField(default='¡Hola! Te invito a unirte a Clanship. Regístrate usando mi código de asociado {code} para contactarme y encontrar los mejores especialistas: https://clanship.cl', help_text='Variable disponible: {code} (código único del maestro)', verbose_name='Mensaje para compartir (WhatsApp/Redes)')),
                ('how_it_works_title', models.CharField(default='¿Cómo funciona?', max_length=100, verbose_name='Título: ¿Cómo funciona?')),
                ('step_1', models.CharField(default='Comparte tu código con clientes o colegas.', max_length=300, verbose_name='Paso 1')),
                ('step_2', models.CharField(default='Al registrarse en Clanship, ingresan tu código.', max_length=300, verbose_name='Paso 2')),
                ('step_3', models.CharField(default='Al completar {target} asociados, ganas automáticamente {days} días de {plan}.', help_text='Variables disponibles: {target}, {days}, {plan}', max_length=300, verbose_name='Paso 3')),
                ('banner_title', models.CharField(default='Mi Código de Asociado', max_length=100, verbose_name='Título de banner en perfil')),
                ('banner_subtitle', models.CharField(default='Invita {target} asociados y gana un plan gratis', help_text='Variables disponibles: {target}, {days}, {plan}', max_length=200, verbose_name='Subtítulo de banner en perfil')),
                ('my_plan_invite_text', models.CharField(default='Invita {target} asociados y gana {days} días gratis de {plan}.', help_text='Variables disponibles: {target}, {days}, {plan}', max_length=200, verbose_name='Texto de invitación en Mi Plan')),
                ('active_benefit_text', models.CharField(default='Beneficio de plan activo hasta el {date}', help_text='Variable disponible: {date}', max_length=200, verbose_name='Texto de beneficio activo')),
                ('notification_new_referral', models.CharField(default='¡{name} se inscribió con tu código de asociado! Llevas {pending} de {target} para tu beneficio.', help_text='Variables disponibles: {name}, {pending}, {target}', max_length=300, verbose_name='Notificación: Nuevo asociado inscrito')),
                ('notification_reward_earned', models.CharField(default='¡Felicidades! Completaste tu meta de {target} asociados. Ganaste {days} días de {plan} gratis.', help_text='Variables disponibles: {target}, {days}, {plan}', max_length=300, verbose_name='Notificación: Meta alcanzada (Beneficio ganado)')),
                ('registration_code_label', models.CharField(default='Código de asociado o invitación (Opcional)', max_length=200, verbose_name='Etiqueta de campo en registro')),
                ('registration_code_hint', models.CharField(default='Ej: CLAN-ABC12', max_length=100, verbose_name='Texto de ayuda / Placeholder en registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Contenido de Programa de Asociados',
                'verbose_name_plural': 'Contenidos de Programa de Asociados (por Idioma)',
                'ordering': ['language'],
            },
        ),
        migrations.RunPython(seed_initial_content, migrations.RunPython.noop),
    ]

