# Generated by Django 4.2.30 on 2026-09-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_referralprogramcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='referral_max_rewards_per_user',
            field=models.PositiveIntegerField(default=1, help_text='Veces máximas que un maestro puede ganar el beneficio del plan (0 = Ilimitado)', verbose_name='Límite de beneficios por maestro'),
        ),
    ]
