# Generated by Django 4.2.30 on 2026-09-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_systemsetting_referral_max_rewards_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='subscriptions_blocked_versions_android',
            field=models.CharField(blank=True, default='', help_text='Versiones separadas por coma que NO mostrarán planes en Android (ej: 1.0.6). Dejar en blanco si no aplica.', max_length=255, verbose_name='Versiones bloqueadas en Android'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='subscriptions_blocked_versions_ios',
            field=models.CharField(blank=True, default='', help_text='Versiones separadas por coma que NO mostrarán planes (ej: 1.0.6, 1.0.7). Útil cuando una versión específica está en revisión.', max_length=255, verbose_name='Versiones bloqueadas en iOS (revisión de Apple)'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='subscriptions_min_version_android',
            field=models.CharField(blank=True, default='', help_text='Versión mínima requerida (ej: 1.0.5) para mostrar planes en Android. Dejar en blanco si no aplica.', max_length=20, verbose_name='Versión mínima para suscripciones en Android'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='subscriptions_min_version_ios',
            field=models.CharField(blank=True, default='', help_text='Versión mínima requerida (ej: 1.0.5) para mostrar planes en iOS. Dejar en blanco si no aplica.', max_length=20, verbose_name='Versión mínima para suscripciones en iOS'),
        ),
    ]
