# Generated by Django 4.2.30 on 2026-09-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_systemsetting_subscriptions_blocked_versions_android_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='nationwide_coverage_mode',
            field=models.BooleanField(default=False, help_text='Si está activo, los clientes pueden ver y contratar a maestros de todo el país, ignorando los límites de radio de movilidad individuales.', verbose_name='Modo Cobertura Nacional (Todo Chile)'),
        ),
    ]
