# Generated by Django 4.2.30 on 2026-09-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_systemsetting_nationwide_coverage_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalprofile',
            name='latitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=9, max_digits=12, null=True, verbose_name='Latitud Profesional'),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='longitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=9, max_digits=12, null=True, verbose_name='Longitud Profesional'),
        ),
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=9, max_digits=12, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=9, max_digits=12, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='Número de Teléfono'),
        ),
    ]
