# Generated by Django 4.2.30 on 2026-09-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_alter_professionalprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversionconfig',
            name='shorebird_mandatory',
            field=models.BooleanField(default=False, help_text='Si está activo, obliga a descargar el último parche OTA antes de usar la app.', verbose_name='Shorebird Patch Obligatorio'),
        ),
    ]
