# Generated by Django 4.2.30 on 2026-10-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_appversionconfig_shorebird_mandatory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Subtítulo')),
                ('image', models.ImageField(blank=True, help_text='Opcional. Si no se sube, se usará el gradiente de colores.', null=True, upload_to='banners/', verbose_name='Imagen de Fondo')),
                ('gradient_start', models.CharField(default='#4299e1', help_text='Ej: #4299e1', max_length=7, verbose_name='Color Gradiente Inicio (Hex)')),
                ('gradient_end', models.CharField(default='#2b6cb0', help_text='Ej: #2b6cb0', max_length=7, verbose_name='Color Gradiente Fin (Hex)')),
                ('cta_text', models.CharField(default='Ver más', max_length=50, verbose_name='Texto del Botón')),
                ('external_link', models.URLField(blank=True, help_text='Si se llena, al tocar el botón abrirá este enlace web.', null=True, verbose_name='Enlace Externo')),
                ('internal_route', models.CharField(blank=True, help_text='Ej: /profile, /settings. Ignorado si hay Enlace Externo.', max_length=100, null=True, verbose_name='Ruta Interna de la App')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('app_type', models.CharField(choices=[('ALL', 'Ambas aplicaciones'), ('CLIENT', 'Solo Cliente'), ('TRADESMAN', 'Solo Especialista')], default='ALL', max_length=20, verbose_name='Mostrar en')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Los banners con menor número aparecen primero.', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Banner de Inicio',
                'verbose_name_plural': 'Banners de Inicio',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
