# Generated by Django 4.2.30 on 2026-10-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversionconfig',
            name='shorebird_minimum_version',
            field=models.IntegerField(default=0, help_text='Número de parche mínimo requerido por Shorebird para poder usar la app.', verbose_name='Shorebird Patch Mínimo'),
        ),
    ]
