# Generated by Django 4.2.30 on 2026-05-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(verbose_name='Fecha programada')),
                ('scheduled_time', models.TimeField(verbose_name='Hora programada')),
                ('status', models.CharField(choices=[('AGREED', 'Acordado'), ('IN_VISIT', 'En Visita'), ('FINISHED', 'Finalizado'), ('CANCELLED', 'Cancelado')], default='AGREED', max_length=20, verbose_name='Estado')),
                ('description', models.TextField(verbose_name='Descripción del trabajo')),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio acordado')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección de la visita')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trabajo',
                'verbose_name_plural': 'Trabajos',
            },
        ),
    ]
