# Generated by Django 4.2.30 on 2026-05-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección de la visita'),
        ),
        migrations.AlterField(
            model_name='job',
            name='agreed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio acordado'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción del trabajo'),
        ),
        migrations.AlterField(
            model_name='job',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha programada'),
        ),
        migrations.AlterField(
            model_name='job',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora programada'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Solicitado'), ('AGREED', 'Acordado'), ('IN_VISIT', 'En Visita'), ('FINISHED', 'Finalizado'), ('CANCELLED', 'Cancelado')], default='REQUESTED', max_length=20, verbose_name='Estado'),
        ),
    ]
