# Generated by Django 4.2.30 on 2026-06-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_address_alter_job_agreed_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Leído por el profesional'),
        ),
    ]
