# Generated by Django 4.2.30 on 2026-07-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='additional_photo',
            field=models.ImageField(blank=True, null=True, upload_to='job_photos/', verbose_name='Foto adicional'),
        ),
        migrations.AddField(
            model_name='job',
            name='enriched_details',
            field=models.TextField(blank=True, null=True, verbose_name='Detalles adicionales'),
        ),
        migrations.AddField(
            model_name='job',
            name='lead_notification_sent',
            field=models.BooleanField(default=False, verbose_name='Notificación de aviso previo enviada'),
        ),
        migrations.AddField(
            model_name='job',
            name='notification_lead_minutes',
            field=models.IntegerField(default=60, verbose_name='Minutos de aviso push previo'),
        ),
    ]
