# Generated by Django 4.2.30 on 2026-07-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_additional_photo_job_enriched_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Solicitado'), ('SCHEDULED', 'Propuesto por Confirmar'), ('AGREED', 'Acordado'), ('IN_VISIT', 'En Visita'), ('FINISHED', 'Finalizado'), ('CANCELLED', 'Cancelado')], default='REQUESTED', max_length=20, verbose_name='Estado'),
        ),
    ]
