# Generated by Django 4.2.30 on 2026-07-21 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0006_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Razón de cancelación/rechazo'),
        ),
        migrations.AddField(
            model_name='job',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Cancelado por'),
        ),
    ]
