# Generated by Django 4.2.30 on 2026-07-28 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0022_subscriptionplan_features'),
        ('jobs', '0008_jobreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicJobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título del servicio')),
                ('description', models.TextField(verbose_name='Descripción detallada')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección de la visita')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='public_job_photos/', verbose_name='Fotografía del problema')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Presupuesto estimado')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Urgente')),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('ASSIGNED', 'Asignada'), ('CANCELLED', 'Cancelada'), ('EXPIRED', 'Expirada')], default='OPEN', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de expiración')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_job_requests', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_job_requests', to='users.specialty', verbose_name='Especialidad requerida')),
            ],
            options={
                'verbose_name': 'Solicitud Abierta',
                'verbose_name_plural': 'Solicitudes Abiertas',
            },
        ),
        migrations.CreateModel(
            name='JobProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio cotizado')),
                ('scheduled_date', models.DateField(verbose_name='Fecha propuesta')),
                ('scheduled_time', models.TimeField(verbose_name='Hora propuesta')),
                ('message', models.TextField(blank=True, verbose_name='Mensaje para el cliente')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ACCEPTED', 'Aceptada'), ('REJECTED', 'Rechazada')], default='PENDING', max_length=20, verbose_name='Estado de la propuesta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Profesional')),
                ('public_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='jobs.publicjobrequest', verbose_name='Solicitud Abierta')),
            ],
            options={
                'verbose_name': 'Propuesta de Trabajo',
                'verbose_name_plural': 'Propuestas de Trabajo',
                'unique_together': {('public_request', 'professional')},
            },
        ),
    ]
