# Generated by Django 4.2.30 on 2026-07-28 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_subscriptionplan_features'),
        ('jobs', '0009_publicjobrequest_jobproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicjobrequest',
            name='custom_specialty',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Especialidad personalizada'),
        ),
        migrations.AlterField(
            model_name='publicjobrequest',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_job_requests', to='users.specialty', verbose_name='Especialidad requerida'),
        ),
    ]
