# Generated by Django 4.2.30 on 2026-07-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_publicjobrequest_custom_specialty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicjobrequest',
            name='desired_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha deseada del trabajo'),
        ),
        migrations.AddField(
            model_name='publicjobrequest',
            name='photos',
            field=models.JSONField(blank=True, default=list, verbose_name='Fotografías del problema (máximo 4)'),
        ),
    ]
