# Generated by Django 4.2.30 on 2026-08-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_publicjobrequest_desired_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Solicitado'), ('SCHEDULED', 'Propuesto por Confirmar'), ('AGREED', 'Acordado'), ('IN_VISIT', 'En Visita'), ('FINISHED', 'Finalizado'), ('CANCELLED', 'Cancelado')], db_index=True, default='REQUESTED', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', '-created_at'], name='jobs_job_status_57b86b_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['customer', 'status'], name='jobs_job_custome_522329_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['professional', 'status'], name='jobs_job_profess_12335f_idx'),
        ),
    ]
