# Generated by Django 4.2.30 on 2026-09-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_job_created_at_alter_job_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicjobrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='publicjobrequest',
            name='latitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='publicjobrequest',
            name='longitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='publicjobrequest',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Abierta'), ('ASSIGNED', 'Asignada'), ('CANCELLED', 'Cancelada'), ('EXPIRED', 'Expirada')], db_index=True, default='OPEN', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddIndex(
            model_name='jobproposal',
            index=models.Index(fields=['public_request', '-created_at'], name='jobs_jobpro_public__0cee91_idx'),
        ),
        migrations.AddIndex(
            model_name='publicjobrequest',
            index=models.Index(fields=['status', '-created_at'], name='jobs_public_status_28b860_idx'),
        ),
        migrations.AddIndex(
            model_name='publicjobrequest',
            index=models.Index(fields=['latitude', 'longitude'], name='jobs_public_latitud_06c554_idx'),
        ),
    ]
