# Generated by Django 4.2.30 on 2026-09-29 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_alter_publicjobrequest_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobProposalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='proposal_attachments/', verbose_name='Archivo')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo de archivo (MIME)')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre original del archivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='jobs.jobproposal', verbose_name='Cotización/Propuesta')),
            ],
            options={
                'verbose_name': 'Adjunto de Propuesta',
                'verbose_name_plural': 'Adjuntos de Propuesta',
            },
        ),
    ]
