# Generated by Django 4.2.30 on 2026-10-01 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0014_jobproposalattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(verbose_name='Detalles del reclamo')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_REVIEW', 'En Revisión'), ('RESOLVED', 'Resuelto'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20, verbose_name='Estado del reclamo')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notas internas (Soporte)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_claims', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='jobs.job', verbose_name='Trabajo')),
            ],
            options={
                'verbose_name': 'Reclamo de Trabajo',
                'verbose_name_plural': 'Reclamos de Trabajos',
                'indexes': [models.Index(fields=['status', '-created_at'], name='jobs_jobcla_status_e5fbfa_idx')],
            },
        ),
    ]
