# Generated by Django 4.2.30 on 2026-10-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_jobclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio final cobrado'),
        ),
        migrations.AddField(
            model_name='job',
            name='finished_photos',
            field=models.JSONField(blank=True, default=list, verbose_name='Fotos del trabajo terminado'),
        ),
        migrations.AddField(
            model_name='job',
            name='tradesman_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios del profesional al finalizar'),
        ),
    ]
