# Generated by Django 4.2.30 on 2026-10-06 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_job_final_price_job_finished_photos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobClaimAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='claim_attachments/', verbose_name='Archivo')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo de archivo (MIME)')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='jobs.jobclaim', verbose_name='Reclamo')),
            ],
        ),
    ]
