# Generated by Django 4.2.30 on 2026-07-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatroom_unique_together_chatroom_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/', verbose_name='Archivo adjunto'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'Texto'), ('IMAGE', 'Imagen'), ('AUDIO', 'Audio')], default='TEXT', max_length=10, verbose_name='Tipo de mensaje'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje'),
        ),
    ]
