# Generated by Django 4.2.30 on 2026-07-17 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0006_alter_job_status'),
        ('chat', '0004_message_file_message_message_type_alter_message_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_room', to='jobs.job', verbose_name='Trabajo asociado'),
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('customer', 'professional')},
        ),
    ]
