# Generated by Django 4.2.30 on 2026-07-17 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def deduplicate_chats(apps, schema_editor):
    ChatRoom = apps.get_model('chat', 'ChatRoom')
    Message = apps.get_model('chat', 'Message')
    
    rooms = ChatRoom.objects.all()
    from collections import defaultdict
    grouped = defaultdict(list)
    for r in rooms:
        grouped[(r.customer_id, r.professional_id)].append(r)
        
    for key, room_list in grouped.items():
        if len(room_list) > 1:
            room_list.sort(key=lambda r: r.id)
            primary_room = room_list[0]
            duplicate_rooms = room_list[1:]
            
            for dup in duplicate_rooms:
                # Reassign all messages of the duplicate chat room to the primary one
                Message.objects.filter(room=dup).update(room=primary_room)
                
                # If duplicate has a job and primary doesn't, link it to the primary
                if dup.job_id and not primary_room.job_id:
                    primary_room.job_id = dup.job_id
                    primary_room.save()
                
                # Dissociate job and delete duplicate room safely
                dup.job_id = None
                dup.save()
                dup.delete()

class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0006_alter_job_status'),
        ('chat', '0004_message_file_message_message_type_alter_message_text'),
    ]

    operations = [
        migrations.RunPython(deduplicate_chats, elidable=True),
        migrations.AlterField(
            model_name='chatroom',
            name='job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_room', to='jobs.job', verbose_name='Trabajo asociado'),
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('customer', 'professional')},
        ),
    ]
